// Certifica-te de que os caminhos './definition' e './faker'
// correspondem aos nomes exatos dos teus ficheiros
import fs from 'fs'
import path from 'path'
import type { LocaleDefinition } from './definitions.ts'
import { MyFaker, Person } from './faker'

// 1. Criar a nossa "Base de Dados" de teste
const pt_PT: LocaleDefinition = {
  person: {
    gender: ['Mulher', 'Homem', 'Não-binário', 'Género Fluido'],
    sex: ['female', 'male'],
    first_name: {
      female: [
        'Maria',
        'Leonor',
        'Matilde',
        'Mariana',
        'Ana',
        'Beatriz',
        'Inês',
        'Lara',
        'Carolina',
        'Margarida',
        'Joana',
        'Sofia',
        'Diana',
        'Francisca',
        'Laura',
        'Sara',
        'Madalena',
        'Rita',
        'Mafalda',
        'Catarina',
        'Luana',
        'Marta',
        'Íris',
        'Alice',
        'Bianca',
        'Constança',
        'Gabriela',
        'Eva',
        'Clara',
        'Bruna',
        'Daniela',
        'Iara',
        'Filipa',
        'Vitória',
        'Ariana',
        'Letícia',
        'Bárbara',
        'Camila',
        'Rafaela',
        'Carlota',
        'Yara',
        'Núria',
        'Raquel',
        'Ema',
        'Helena',
        'Benedita',
        'Érica',
        'Isabel',
        'Nicole',
        'Lia',
        'Alícia',
        'Mara',
        'Jéssica',
        'Soraia',
        'Júlia',
        'Luna',
        'Victória',
        'Luísa',
        'Teresa',
        'Miriam',
        'Adriana',
        'Melissa',
        'Andreia',
        'Juliana',
        'Alexandra',
        'Yasmin',
        'Tatiana',
        'Leticia',
        'Luciana',
        'Eduarda',
        'Cláudia',
        'Débora',
        'Fabiana',
        'Renata',
        'Kyara',
        'Kelly',
        'Irina',
        'Mélanie',
        'Nádia',
        'Cristiana',
        'Liliana',
        'Patrícia',
        'Vera',
        'Doriana',
        'Ângela',
        'Mia',
        'Erica',
        'Mónica',
        'Isabela',
        'Salomé',
        'Cátia',
        'Verónica',
        'Violeta',
        'Lorena',
        'Érika',
        'Vanessa',
        'Iris',
        'Anna',
        'Viviane',
        'Rebeca',
        'Neuza',
      ],

      male: [
        'Rodrigo',
        'João',
        'Martim',
        'Afonso',
        'Tomás',
        'Gonçalo',
        'Francisco',
        'Tiago',
        'Diogo',
        'Guilherme',
        'Pedro',
        'Miguel',
        'Rafael',
        'Gabriel',
        'Santiago',
        'Dinis',
        'David',
        'Duarte',
        'José',
        'Simão',
        'Daniel',
        'Lucas',
        'Gustavo',
        'André',
        'Denis',
        'Salvador',
        'António',
        'Vasco',
        'Henrique',
        'Lourenço',
        'Manuel',
        'Eduardo',
        'Bernardo',
        'Leandro',
        'Luís',
        'Diego',
        'Leonardo',
        'Alexandre',
        'Rúben',
        'Mateus',
        'Ricardo',
        'Vicente',
        'Filipe',
        'Bruno',
        'Nuno',
        'Carlos',
        'Rui',
        'Hugo',
        'Samuel',
        'Álvaro',
        'Matias',
        'Fábio',
        'Ivo',
        'Paulo',
        'Jorge',
        'Xavier',
        'Marco',
        'Isaac',
        'Raúl',
        'Benjamim',
        'Renato',
        'Artur',
        'Mário',
        'Frederico',
        'Cristiano',
        'Ivan',
        'Sérgio',
        'Micael',
        'Vítor',
        'Edgar',
        'Kevin',
        'Joaquim',
        'Igor',
        'Ângelo',
        'Enzo',
        'Valentim',
        'Flávio',
        'Joel',
        'Fernando',
        'Sebastião',
        'Tomé',
        'César',
        'Cláudio',
        'Nelson',
        'Lisandro',
        'Jaime',
        'Gil',
        'Mauro',
        'Sandro',
        'Hélder',
        'Matheus',
        'William',
        'Gaspar',
        'Márcio',
        'Martinho',
        'Emanuel',
        'Marcos',
        'Telmo',
        'Davi',
        'Wilson',
      ],
    },
    last_name: {
      generic: [
        'Abreu',
        'Almeida',
        'Alves',
        'Amaral',
        'Amorim',
        'Andrade',
        'Anjos',
        'Antunes',
        'Araújo',
        'Assunção',
        'Azevedo',
        'Baptista',
        'Barbosa',
        'Barros',
        'Batista',
        'Borges',
        'Branco',
        'Brito',
        'Campos',
        'Cardoso',
        'Carneiro',
        'Carvalho',
        'Castro',
        'Coelho',
        'Correia',
        'Costa',
        'Cruz',
        'Cunha',
        'Domingues',
        'Esteves',
        'Faria',
        'Fernandes',
        'Ferreira',
        'Figueiredo',
        'Fonseca',
        'Freitas',
        'Garcia',
        'Gaspar',
        'Gomes',
        'Gonçalves',
        'Guerreiro',
        'Henriques',
        'Jesus',
        'Leal',
        'Leite',
        'Lima',
        'Lopes',
        'Loureiro',
        'Lourenço',
        'Macedo',
        'Machado',
        'Magalhães',
        'Maia',
        'Marques',
        'Martins',
        'Matias',
        'Matos',
        'Melo',
        'Mendes',
        'Miranda',
        'Monteiro',
        'Morais',
        'Moreira',
        'Mota',
        'Moura',
        'Nascimento',
        'Neto',
        'Neves',
        'Nogueira',
        'Nunes',
        'Oliveira',
        'Pacheco',
        'Paiva',
        'Pereira',
        'Pinheiro',
        'Pinho',
        'Pinto',
        'Pires',
        'Ramos',
        'Reis',
        'Ribeiro',
        'Rocha',
        'Rodrigues',
        'Santos',
        'Silva',
        'Simões',
        'Soares',
        'Sousa',
        'Sá',
        'Tavares',
        'Teixeira',
        'Torres',
        'Valente',
        'Vaz',
        'Vicente',
        'Vieira',
      ],
    },

    // Os nossos padrões de Mustache com pesos
    name: [
      { value: '{{person.firstName}} {{person.lastName}}', weight: 10 },
      { value: '{{person.firstName}} {{person.lastName}}', weight: 3 },
      { value: '{{person.firstName}}  {{person.lastName}}', weight: 5 },
    ],
    last_name_pattern: { generic: [{ value: '{{person.lastName}}', weight: 1 }] },

    // Arrays vazios para preencher os restantes requisitos do teu tipo PersonDefinition
    bio_pattern: [],
    job_descriptor: [],
    job_area: [],
    job_type: [],
    job_title_pattern: [],
  },
}

// 2. Inicializar o nosso Faker personalizado com os dados
const myFakerInstance = new MyFaker(pt_PT)
const personFaker = new Person(myFakerInstance)

// 3. Obter caminhos de ficheiro utilizando o CWD (Current Working Directory)
const baseDir = path.join(process.cwd(), 'backend', 'faker')
const usersJsonPath = path.join(baseDir, 'users.json')

// Apagar o ficheiro users.json se existir antes de correr a geração
if (fs.existsSync(usersJsonPath)) {
  try {
    fs.unlinkSync(usersJsonPath)
    console.log('\x1b[33m✔ Dados antigos de users.json apagados.\x1b[0m')
  } catch (error) {
    console.error('\x1b[31m✖ Erro ao apagar users.json:\x1b[0m', error)
  }
}

// 4. Gerar utilizadores fictícios
const numUsers = 30
const generatedUsers = []
let artistCounter = 1

for (let i = 0; i < numUsers; i++) {
  // Gera uma mistura de utilizadores normais e artistas
  const isArtist = Math.random() < 0.3
  const id_conta = i + 1
  const id_artista = isArtist ? artistCounter++ : null

  const user = personFaker.account({
    id_conta,
    id_artista
  })
  generatedUsers.push(user)
}

// 5. Gravar os dados em users.json
try {
  const jsonContent = JSON.stringify(generatedUsers, null, 2)
  
  fs.writeFileSync(usersJsonPath, jsonContent, 'utf-8')
  
  console.log(`\n\x1b[32m✔ Sucesso! Foram gerados ${numUsers} utilizadores.\x1b[0m`)
  console.log(`\x1b[34m→ Gravado em: ${usersJsonPath}\x1b[0m`)
} catch (error) {
  console.error('\x1b[31m✖ Erro ao gravar ficheiros JSON:\x1b[0m', error)
}
